### ISSUE TITLE
support for ceph radosgw (onsite s3)

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry-community/s3-cf-service-broker#9]
is there a possibility to set the host?
because ceph(radosgw) have almost full s3 support
see http://docs.ceph.com/docs/master/radosgw/s3/

we already use ceph for cf droplets

```
    droplets:
      droplet_directory_key: <%= root_domain %>-cc-droplets-new
      fog_connection:
        provider: "AWS"
        host: "s3.eden.klm.com"
        scheme: "http"
        port: 80
        aws_signature_version: "2"
        aws_access_key_id: "XXXXXXXXXXXXXXXXXX
        aws_secret_access_key: "XXXXXXXXXXXXXXXXXXXXXXX"
```

so we only need to be able to set ( host, scheme, port, aws_signature_version )
